-- 나라장터 용역 입찰공고(getBidPblancListInfoServc) + 수집 로그
-- Supabase SQL Editor에서 실행하거나 apply 스크립트로 적용하십시오.

create table if not exists public.bid_pblanc_servc (
  id bigint generated by default as identity primary key,
  bid_ntce_no text not null,
  bid_ntce_ord text not null default '00',
  bid_ntce_nm text not null default '',
  ntce_instt_nm text not null default '',
  dminstt_nm text not null default '',
  bid_methd_nm text not null default '',
  cntrct_cncls_mthd_nm text not null default '',
  ntce_dt text not null default '',
  bid_clse_dt text not null default '',
  openg_dt text not null default '',
  presmpt_prce numeric,
  bdgt_amt numeric,
  bsns_div_nm text not null default '',
  re_ntce_yn text not null default '',
  bid_ntce_dtl_url text not null default '',
  bid_ntce_url text not null default '',
  page_no integer not null default 1,
  raw jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (bid_ntce_no, bid_ntce_ord)
);

create index if not exists bid_pblanc_servc_fetched_at_idx
  on public.bid_pblanc_servc (fetched_at desc);

create index if not exists bid_pblanc_servc_ntce_dt_idx
  on public.bid_pblanc_servc (ntce_dt desc);

create index if not exists bid_pblanc_servc_instt_idx
  on public.bid_pblanc_servc (ntce_instt_nm, dminstt_nm);

create index if not exists bid_pblanc_servc_method_idx
  on public.bid_pblanc_servc (cntrct_cncls_mthd_nm, bid_methd_nm);

alter table public.bid_pblanc_servc enable row level security;

drop policy if exists "public can read bid pblanc servc"
  on public.bid_pblanc_servc;
create policy "public can read bid pblanc servc"
  on public.bid_pblanc_servc
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can upsert bid pblanc servc"
  on public.bid_pblanc_servc;
create policy "anon can upsert bid pblanc servc"
  on public.bid_pblanc_servc
  for insert to anon, authenticated
  with check (true);

drop policy if exists "anon can update bid pblanc servc"
  on public.bid_pblanc_servc;
create policy "anon can update bid pblanc servc"
  on public.bid_pblanc_servc
  for update to anon, authenticated
  using (true)
  with check (true);

create table if not exists public.bid_pblanc_servc_fetch_logs (
  id bigint generated by default as identity primary key,
  page_no integer not null default 1,
  page_size integer not null default 100,
  row_count integer not null default 0 check (row_count >= 0),
  total_count integer not null default 0,
  params jsonb not null default '{}'::jsonb,
  status text not null default 'ok' check (status in ('ok', 'error')),
  error_message text not null default '',
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists bid_pblanc_servc_fetch_logs_fetched_at_idx
  on public.bid_pblanc_servc_fetch_logs (fetched_at desc);

alter table public.bid_pblanc_servc_fetch_logs enable row level security;

drop policy if exists "public can read bid pblanc servc fetch logs"
  on public.bid_pblanc_servc_fetch_logs;
create policy "public can read bid pblanc servc fetch logs"
  on public.bid_pblanc_servc_fetch_logs
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can insert bid pblanc servc fetch logs"
  on public.bid_pblanc_servc_fetch_logs;
create policy "anon can insert bid pblanc servc fetch logs"
  on public.bid_pblanc_servc_fetch_logs
  for insert to anon, authenticated
  with check (true);
