-- GH 주택청약·임대센터 공개 청약공고 + 수집 로그

create table if not exists public.gh_sale_notices (
  id bigint generated by default as identity primary key,
  source_type text not null,
  source_label text not null default '',
  pbanc_no text not null,
  notice_type text not null default '',
  title text not null default '',
  region text not null default '',
  posted_at text not null default '',
  closed_at text not null default '',
  status text not null default '',
  views integer not null default 0,
  detail_url text not null default '',
  source_url text not null default '',
  raw jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (source_type, pbanc_no)
);

create index if not exists gh_sale_notices_posted_at_idx
  on public.gh_sale_notices (posted_at desc, fetched_at desc);

create index if not exists gh_sale_notices_region_idx
  on public.gh_sale_notices (region, source_type);

alter table public.gh_sale_notices enable row level security;

drop policy if exists "public can read gh sale notices"
  on public.gh_sale_notices;
create policy "public can read gh sale notices"
  on public.gh_sale_notices
  for select to anon, authenticated
  using (true);

create table if not exists public.gh_sale_fetch_logs (
  id bigint generated by default as identity primary key,
  row_count integer not null default 0 check (row_count >= 0),
  saved_count integer not null default 0 check (saved_count >= 0),
  source_status jsonb not null default '[]'::jsonb,
  status text not null default 'ok' check (status in ('ok', 'error')),
  error_message text not null default '',
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists gh_sale_fetch_logs_fetched_at_idx
  on public.gh_sale_fetch_logs (fetched_at desc);

alter table public.gh_sale_fetch_logs enable row level security;

drop policy if exists "public can read gh sale fetch logs"
  on public.gh_sale_fetch_logs;
create policy "public can read gh sale fetch logs"
  on public.gh_sale_fetch_logs
  for select to anon, authenticated
  using (true);
