create table if not exists public.hwaseong_real_estate (
  id bigint generated by default as identity primary key,
  transaction_key text not null unique,
  global_index integer not null,
  deal_month text not null check (deal_month ~ '^\d{4}-\d{2}$'),
  district_code text not null,
  district_name text not null,
  neighborhood text not null default '',
  apartment_name text not null,
  deal_date date not null,
  price_manwon integer not null check (price_manwon >= 0),
  area_sqm numeric(10,4) not null check (area_sqm >= 0),
  price_per_sqm_manwon numeric(12,2) not null default 0,
  floor integer not null default 0,
  build_year integer not null default 0,
  jibun text not null default '',
  deal_type text not null default '',
  agent_location text not null default '',
  buyer_type text not null default '',
  seller_type text not null default '',
  cancellation_date text not null default '',
  registration_date text not null default '',
  synced_at timestamptz not null default now()
);

create index if not exists hwaseong_real_estate_month_date_idx
  on public.hwaseong_real_estate (deal_month,deal_date desc);

create index if not exists hwaseong_real_estate_district_idx
  on public.hwaseong_real_estate (district_code,apartment_name);

alter table public.hwaseong_real_estate enable row level security;

drop policy if exists "public can read hwaseong transactions"
  on public.hwaseong_real_estate;
create policy "public can read hwaseong transactions"
  on public.hwaseong_real_estate
  for select to anon,authenticated
  using (true);

-- INSERT와 UPDATE는 배포 서버의 service_role 키만 수행합니다.
