-- LH 분양정보(분양임대공고문 · 분양주택) + 수집 로그
-- Supabase SQL Editor에서 실행하거나 apply 스크립트로 적용하십시오.

create table if not exists public.lh_sale_notices (
  id bigint generated by default as identity primary key,
  pan_id text not null,
  pan_nm text not null default '',
  upp_ais_tp_cd text not null default '',
  upp_ais_tp_nm text not null default '',
  ais_tp_cd text not null default '',
  ais_tp_cd_nm text not null default '',
  cnp_cd text not null default '',
  cnp_cd_nm text not null default '',
  pan_ss text not null default '',
  pan_nt_st_dt text not null default '',
  clsg_dt text not null default '',
  all_cnt integer not null default 0,
  dtl_url text not null default '',
  spl_inf_tp_cd text not null default '',
  ccr_cnnt_sys_ds_cd text not null default '',
  page_no integer not null default 1,
  raw jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (pan_id)
);

create index if not exists lh_sale_notices_fetched_at_idx
  on public.lh_sale_notices (fetched_at desc);

create index if not exists lh_sale_notices_region_idx
  on public.lh_sale_notices (cnp_cd_nm, pan_ss);

create index if not exists lh_sale_notices_type_idx
  on public.lh_sale_notices (upp_ais_tp_cd, ais_tp_cd_nm);

alter table public.lh_sale_notices enable row level security;

drop policy if exists "public can read lh sale notices"
  on public.lh_sale_notices;
create policy "public can read lh sale notices"
  on public.lh_sale_notices
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can upsert lh sale notices"
  on public.lh_sale_notices;
create policy "anon can upsert lh sale notices"
  on public.lh_sale_notices
  for insert to anon, authenticated
  with check (true);

drop policy if exists "anon can update lh sale notices"
  on public.lh_sale_notices;
create policy "anon can update lh sale notices"
  on public.lh_sale_notices
  for update to anon, authenticated
  using (true)
  with check (true);

create table if not exists public.lh_sale_fetch_logs (
  id bigint generated by default as identity primary key,
  page_no integer not null default 1,
  page_size integer not null default 30,
  row_count integer not null default 0 check (row_count >= 0),
  total_count integer not null default 0,
  params jsonb not null default '{}'::jsonb,
  status text not null default 'ok' check (status in ('ok', 'error')),
  error_message text not null default '',
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists lh_sale_fetch_logs_fetched_at_idx
  on public.lh_sale_fetch_logs (fetched_at desc);

alter table public.lh_sale_fetch_logs enable row level security;

drop policy if exists "public can read lh sale fetch logs"
  on public.lh_sale_fetch_logs;
create policy "public can read lh sale fetch logs"
  on public.lh_sale_fetch_logs
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can insert lh sale fetch logs"
  on public.lh_sale_fetch_logs;
create policy "anon can insert lh sale fetch logs"
  on public.lh_sale_fetch_logs
  for insert to anon, authenticated
  with check (true);
