-- 공공데이터 수집 로그 + CSV Storage 버킷
-- Supabase SQL Editor에서 실행하십시오.

create table if not exists public.public_data_collection_logs (
  id bigint generated by default as identity primary key,
  api_id text not null,
  api_name text not null,
  row_count integer not null default 0 check (row_count >= 0),
  file_name text not null default '',
  storage_path text not null default '',
  public_url text not null default '',
  params jsonb not null default '{}'::jsonb,
  status text not null default 'ok' check (status in ('ok', 'error')),
  error_message text not null default '',
  collected_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists public_data_collection_logs_collected_at_idx
  on public.public_data_collection_logs (collected_at desc);

create index if not exists public_data_collection_logs_api_id_idx
  on public.public_data_collection_logs (api_id, collected_at desc);

alter table public.public_data_collection_logs enable row level security;

drop policy if exists "public can read public data collection logs"
  on public.public_data_collection_logs;
create policy "public can read public data collection logs"
  on public.public_data_collection_logs
  for select to anon, authenticated
  using (true);

-- GitHub Pages(정적 페이지)에서 버튼 수집이 가능하도록 anon INSERT 허용
drop policy if exists "anon can insert public data collection logs"
  on public.public_data_collection_logs;
create policy "anon can insert public data collection logs"
  on public.public_data_collection_logs
  for insert to anon, authenticated
  with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'public-data-csv',
  'public-data-csv',
  true,
  52428800,
  array['text/csv', 'text/plain', 'application/csv']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can read public-data-csv"
  on storage.objects;
create policy "public can read public-data-csv"
  on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'public-data-csv');

drop policy if exists "anon can upload public-data-csv"
  on storage.objects;
create policy "anon can upload public-data-csv"
  on storage.objects
  for insert to anon, authenticated
  with check (bucket_id = 'public-data-csv');

drop policy if exists "anon can update public-data-csv"
  on storage.objects;
create policy "anon can update public-data-csv"
  on storage.objects
  for update to anon, authenticated
  using (bucket_id = 'public-data-csv')
  with check (bucket_id = 'public-data-csv');

-- applied via Actions on push
