-- STARGATE 독서기록 CMS schema
create table if not exists public.reading_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.reading_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  publisher text not null default '',
  genre text not null default '기타',
  rating smallint not null default 5 check (rating between 1 and 5),
  started_at date,
  finished_at date not null,
  pages integer not null default 0 check (pages >= 0),
  reading_days integer not null default 0 check (reading_days >= 0),
  cover_color_1 text not null default '#243b55',
  cover_color_2 text not null default '#141e30',
  one_line text not null default '',
  review text not null default '',
  quotes jsonb not null default '[]'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  is_published boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reading_posts_published_finished_idx
  on public.reading_posts (is_published, finished_at desc);

create or replace function public.set_reading_updated_at()
returns trigger language plpgsql security invoker set search_path = public as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists trg_reading_posts_updated_at on public.reading_posts;
create trigger trg_reading_posts_updated_at before update on public.reading_posts
for each row execute function public.set_reading_updated_at();

alter table public.reading_admins enable row level security;
alter table public.reading_posts enable row level security;

drop policy if exists "reading admins can read self" on public.reading_admins;
create policy "reading admins can read self" on public.reading_admins
for select to authenticated using (user_id = auth.uid());

drop policy if exists "public can read published reading posts" on public.reading_posts;
create policy "public can read published reading posts" on public.reading_posts
for select to anon, authenticated using (
  is_published = true
  or exists (select 1 from public.reading_admins a where a.user_id = auth.uid())
);

drop policy if exists "reading admins can insert" on public.reading_posts;
create policy "reading admins can insert" on public.reading_posts
for insert to authenticated with check (
  exists (select 1 from public.reading_admins a where a.user_id = auth.uid())
);

drop policy if exists "reading admins can update" on public.reading_posts;
create policy "reading admins can update" on public.reading_posts
for update to authenticated using (
  exists (select 1 from public.reading_admins a where a.user_id = auth.uid())
) with check (
  exists (select 1 from public.reading_admins a where a.user_id = auth.uid())
);

drop policy if exists "reading admins can delete" on public.reading_posts;
create policy "reading admins can delete" on public.reading_posts
for delete to authenticated using (
  exists (select 1 from public.reading_admins a where a.user_id = auth.uid())
);

insert into public.reading_posts
(title,author,publisher,genre,rating,started_at,finished_at,pages,reading_days,cover_color_1,cover_color_2,one_line,review,quotes,recommendations,tags,is_published)
select * from (values
('물고기는 존재하지 않는다','룰루 밀러','곰출판','과학·에세이',5,'2026-07-05'::date,'2026-07-11'::date,328,7,'#243b55','#141e30','''물고기''라는 분류는 사실 존재하지 않는다 — 혼돈 앞에서 의미를 붙드는 일에 대하여.','분류학자 데이비드 스타 조던의 집요한 인생을 따라가며 무의미한 세계에서 어떻게 살아갈 것인가를 묻는 과학 논픽션이자 회고록.','[{"t":"혼돈은 언제나 다시 찾아온다. 그러니 우리가 할 수 있는 건, 그 앞에서 무너지지 않을 이유를 스스로 만들어내는 것뿐이다.","s":"본문 중"}]'::jsonb,'["인생의 의미를 잃은 것 같은 시기를 지나는 분","과학과 인문학의 경계를 좋아하는 분","밀도 높은 논픽션을 찾는 분"]'::jsonb,'["회복탄력성","분류학","논픽션","인생책"]'::jsonb,true),
('불편한 편의점','김호연','나무옆의자','소설',4,'2026-06-20','2026-06-24',268,5,'#3a5a40','#1b3021','청파동 골목 편의점에서 벌어지는 다정한 회복의 이야기.','부담 없이 읽히지만 마음에 오래 남는 한국형 힐링 소설.','[{"t":"결국 삶이란, 관계이고 소통이었다. 오래도록 잊고 있던 그 사실을.","s":"본문 중"}]','["잠들기 전 따뜻한 이야기를 원하는 분","한국형 힐링 소설을 좋아하는 분","독서 습관을 다시 만들고 싶은 분"]','["힐링","베스트셀러","한국소설","편의점"]',true),
('클루지','개리 마커스','갤리온','과학·심리',4,'2026-06-01','2026-06-09',320,9,'#4a2c6d','#241238','인간의 마음은 최적 설계가 아니라 그럭저럭 굴러가는 임시변통이다.','확증편향과 비합리적 의사결정을 진화의 누더기 설계로 설명하는 입문서.','[{"t":"진화는 완벽한 것을 만들지 않는다. 다만 이전 것보다 조금 나은 것을 쌓아 올릴 뿐이다.","s":"본문 중"}]','["행동경제학에 처음 입문하는 분","자기 실수를 덜 자책하고 싶은 분","의사결정을 개선하고 싶은 분"]','["인지심리","행동경제학","진화","의사결정"]',true),
('달러구트 꿈 백화점','이미예','팩토리나인','판타지 소설',4,'2026-05-18','2026-05-22',300,5,'#6d4c2c','#3a2712','잠든 사람만 들어갈 수 있는, 꿈을 파는 백화점 이야기.','꿈을 상품으로 만든다는 설정이 돋보이는 따뜻한 판타지.','[{"t":"오늘 밤 당신이 꿀 꿈은, 어쩌면 누군가 정성껏 만들어 진열해 둔 상품일지도 모릅니다.","s":"본문 중"}]','["따뜻한 판타지를 좋아하는 분","짧고 편하게 완독하고 싶은 분","상상력 넘치는 설정을 즐기는 분"]','["판타지","힐링","베스트셀러","꿈"]',true),
('사피엔스','유발 하라리','김영사','역사·인문',5,'2026-04-10','2026-05-02',636,23,'#5a3a2a','#2b1810','허구를 믿는 능력이 어떻게 호모 사피엔스를 지구의 지배종으로 만들었는가.','인지혁명·농업혁명·과학혁명으로 인류사를 관통하는 책.','[{"t":"돈은 지금까지 고안된 것 중 가장 보편적이고 효율적인 상호 신뢰의 시스템이다.","s":"본문 중"}]','["큰 틀에서 인류사를 조망하고 싶은 분","왜 우리는 이렇게 사는가가 궁금한 분","벽돌책 완독에 도전하고 싶은 분"]','["인류사","인문교양","인생책","베스트셀러"]',true),
('미드나잇 라이브러리','매트 헤이그','인플루엔셜','소설',4,'2026-03-22','2026-03-28',416,7,'#1f4e5f','#0e2830','삶과 죽음 사이의 도서관에서, 살지 않은 인생들을 열어보는 여자.','다른 선택을 했다면이라는 상상을 통해 다시 삶을 택하는 과정을 그린 소설.','[{"t":"후회하지 않는 삶이 아니라, 후회를 안고도 나아가는 삶이 필요하다.","s":"본문 중"}]','["요즘 만약에를 자주 떠올리는 분","잔잔한 위로가 필요한 분","번역 소설을 좋아하는 분"]','["위로","번역소설","선택","베스트셀러"]',true)
) as seed(title,author,publisher,genre,rating,started_at,finished_at,pages,reading_days,cover_color_1,cover_color_2,one_line,review,quotes,recommendations,tags,is_published)
where not exists (select 1 from public.reading_posts p where p.title=seed.title);

-- 관리자 Auth 사용자 UUID를 등록하세요.
-- insert into public.reading_admins(user_id) values ('YOUR_AUTH_USER_UUID') on conflict do nothing;
