-- Main portal visitor analytics.
-- Apply in the Supabase SQL editor for project inftexpcnfinglwlrvsj.

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  visit_date date not null,
  path text not null default '/',
  created_at timestamptz not null default now(),
  constraint site_visits_visitor_day_key unique (visitor_id, visit_date),
  constraint site_visits_path_length check (char_length(path) <= 512)
);

create index if not exists site_visits_visit_date_idx
  on public.site_visits (visit_date desc);

alter table public.site_visits enable row level security;
revoke all on table public.site_visits from anon, authenticated;

create or replace function public.record_site_visit(
  p_visitor_id uuid,
  p_visit_date date,
  p_path text default '/'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_rows integer;
begin
  if p_visitor_id is null then
    raise exception 'visitor_id is required';
  end if;

  if p_visit_date <> (timezone('Asia/Seoul', now()))::date then
    raise exception 'visit_date must be the current date in Asia/Seoul';
  end if;

  insert into public.site_visits (visitor_id, visit_date, path)
  values (p_visitor_id, p_visit_date, left(coalesce(nullif(p_path, ''), '/'), 512))
  on conflict (visitor_id, visit_date) do nothing;

  get diagnostics affected_rows = row_count;
  return affected_rows > 0;
end;
$$;

create or replace function public.get_site_visit_stats(p_days integer default 30)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with params as (
    select
      (timezone('Asia/Seoul', now()))::date as today,
      greatest(1, least(coalesce(p_days, 30), 90)) as days
  ),
  dates as (
    select generate_series(
      params.today - (params.days - 1),
      params.today,
      interval '1 day'
    )::date as visit_date
    from params
  ),
  daily as (
    select dates.visit_date, count(site_visits.id)::bigint as visits
    from dates
    left join public.site_visits using (visit_date)
    group by dates.visit_date
    order by dates.visit_date
  )
  select jsonb_build_object(
    'today', coalesce((select visits from daily order by visit_date desc limit 1), 0),
    'total', (select count(*) from public.site_visits),
    'period', (select coalesce(sum(visits), 0) from daily),
    'daily', (
      select coalesce(
        jsonb_agg(jsonb_build_object('date', visit_date, 'visits', visits) order by visit_date),
        '[]'::jsonb
      )
      from daily
    )
  );
$$;

revoke all on function public.record_site_visit(uuid, date, text) from public;
revoke all on function public.get_site_visit_stats(integer) from public;
grant execute on function public.record_site_visit(uuid, date, text) to anon, authenticated;
grant execute on function public.get_site_visit_stats(integer) to anon, authenticated;
